# Generated by Django 4.1.4 on 2023-01-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_chead0_blogpost_chead1_blogpost_chead2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='thumbanil',
            new_name='thumbnail',
        ),
    ]
